title: extremum
description: A learning journey of Duy.
theme: just-the-docs

# url: https://just-the-docs.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template

math: mathjax

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.9.0"

  # For copy button on code
enable_copy_code_button: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top" 

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: green
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: purple
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
